theme: jekyll-theme-minimal
title: "Vincent: an image-based code clone detector"
description: A website accompanying the IWSC 2018 paper "A picture is worth a thousand words: code clone detection based on image similarity.
